In [37]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    confusion_matrix, accuracy_score, recall_score, f1_score,
    roc_auc_score, balanced_accuracy_score
)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers

In [38]:
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

In [39]:
df = pd.read_csv('/kaggle/input/chronic-kidney-disease-dataset-analysis/Chronic_Kidney_Dsease_data.csv')
df.head()

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,1,71,0,0,0,2,31.069414,1,5.128112,1.676220,...,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1,Confidential
1,2,34,0,0,1,3,29.692119,1,18.609552,8.377574,...,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1,Confidential
2,3,80,1,1,0,1,37.394822,1,11.882429,9.607401,...,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1,Confidential
3,4,40,0,2,0,1,31.329680,0,16.020165,0.408871,...,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1,Confidential
4,5,43,0,1,1,2,23.726311,0,7.944146,0.780319,...,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1,Confidential

In [40]:
df = df.drop(columns=["PatientID", "DoctorInCharge"], errors="ignore")
df.head()

,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MuscleCramps,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis
0,71,0,0,0,2,31.069414,1,5.128112,1.676220,0.240386,...,4.518513,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1
1,34,0,0,1,3,29.692119,1,18.609552,8.377574,6.503233,...,2.202222,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1
2,80,1,1,0,1,37.394822,1,11.882429,9.607401,2.104828,...,5.967271,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1
3,40,0,2,0,1,31.329680,0,16.020165,0.408871,6.964422,...,2.176387,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1
4,43,0,1,1,2,23.726311,0,7.944146,0.780319,3.097796,...,6.800993,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            1659 non-null   int64
 1   Gender                         1659 non-null   int64
 2   Ethnicity                      1659 non-null   int64
 3   SocioeconomicStatus            1659 non-null   int64
 4   EducationLevel                 1659 non-null   int64
 5   BMI                            1659 non-null   float64
 6   Smoking                        1659 non-null   int64
 7   AlcoholConsumption             1659 non-null   float64
 8   PhysicalActivity               1659 non-null   float64
 9   DietQuality                    1659 non-null   float64
 10  SleepQuality                   1659 non-null   float64
 11  FamilyHistoryKidneyDisease     1659 non-null   int64
 12  FamilyHistoryHypertension      1659 non-null   int64
 13  FamilyHistoryDiabetes          1659 non-null   int64
 14  PreviousAcuteKidneyInjury      1659 non-null   int64
 15  UrinaryTractInfections         1659 non-null   int64
 16  SystolicBP                     1659 non-null   int64
 17  DiastolicBP                    1659 non-null   int64
 18  FastingBloodSugar              1659 non-null   float64
 19  HbA1c                          1659 non-null   float64
 20  SerumCreatinine                1659 non-null   float64
 21  BUNLevels                      1659 non-null   float64
 22  GFR                            1659 non-null   float64
 23  ProteinInUrine                 1659 non-null   float64
 24  ACR                            1659 non-null   float64
 25  SerumElectrolytesSodium        1659 non-null   float64
 26  SerumElectrolytesPotassium     1659 non-null   float64
 27  SerumElectrolytesCalcium       1659 non-null   float64
 28  SerumElectrolytesPhosphorus    1659 non-null   float64
 29  HemoglobinLevels               1659 non-null   float64
 30  CholesterolTotal               1659 non-null   float64
 31  CholesterolLDL                 1659 non-null   float64
 32  CholesterolHDL                 1659 non-null   float64
 33  CholesterolTriglycerides       1659 non-null   float64
 34  ACEInhibitors                  1659 non-null   int64
 35  Diuretics                      1659 non-null   int64
 36  NSAIDsUse                      1659 non-null   float64
 37  Statins                        1659 non-null   int64
 38  AntidiabeticMedications        1659 non-null   int64
 39  Edema                          1659 non-null   int64
 40  FatigueLevels                  1659 non-null   float64
 41  NauseaVomiting                 1659 non-null   float64
 42  MuscleCramps                   1659 non-null   float64
 43  Itching                        1659 non-null   float64
 44  QualityOfLifeScore             1659 non-null   float64
 45  HeavyMetalsExposure            1659 non-null   int64
 46  OccupationalExposureChemicals  1659 non-null   int64
 47  WaterQuality                   1659 non-null   int64
 48  MedicalCheckupsFrequency       1659 non-null   float64
 49  MedicationAdherence            1659 non-null   float64
 50  HealthLiteracy                 1659 non-null   float64
 51  Diagnosis                      1659 non-null   int64
dtypes: float64(30), int64(22)
memory usage: 674.1 KB

In [42]:
X = df.drop("Diagnosis", axis=1)
y = df["Diagnosis"]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=SEED,
    stratify=y
)

print("Train bincount:", np.bincount(y_train))
print("Test  bincount:", np.bincount(y_test))

Train bincount: [ 108 1219]
Test  bincount: [ 27 305]

In [44]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

In [45]:
# smote = SMOTE(random_state=42, k_neighbors=5)
# X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

In [46]:
# print("Before SMOTE:", np.bincount(y_train))
# print("After  SMOTE:", np.bincount(y_train_smote))

In [47]:
# classes = np.unique(y_train)
# weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
# class_weights = {int(classes[0]): float(weights[0]), int(classes[1]): float(weights[1])}
# print("Class weights:", class_weights)

class_weights = {0: 2.0, 1: 1.0}
print("Class weights:", class_weights)

Class weights: {0: 2.0, 1: 1.0}

In [48]:
from tensorflow import keras
from tensorflow.keras import layers, regularizers

def build_model(input_dim):
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.30),

        layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.25),

        layers.Dense(1, activation="sigmoid"),
    ])
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=5e-4),
        loss="binary_crossentropy",
        metrics=[keras.metrics.BinaryAccuracy(name="acc"), keras.metrics.AUC(name="auc")]
    )
    return model

In [49]:
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

In [50]:
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.20,
    epochs=400,
    batch_size=32,
    callbacks=[early_stop],
    class_weight=class_weights,
    verbose=1
)

Epoch 1/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9189 - auc: 0.8864 - loss: 0.3074 - val_acc: 0.9135 - val_auc: 0.7202 - val_loss: 0.2960
Epoch 2/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9401 - auc: 0.9163 - loss: 0.2679 - val_acc: 0.9023 - val_auc: 0.7332 - val_loss: 0.2988
Epoch 3/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9413 - auc: 0.9399 - loss: 0.2519 - val_acc: 0.8947 - val_auc: 0.7313 - val_loss: 0.3021
Epoch 4/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - auc: 0.9331 - loss: 0.2579 - val_acc: 0.8985 - val_auc: 0.7324 - val_loss: 0.3047
Epoch 5/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9443 - auc: 0.9456 - loss: 0.2427 - val_acc: 0.9023 - val_auc: 0.7373 - val_loss: 0.3083
Epoch 6/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9491 - auc: 0.9341 - loss: 0.2453 - val_acc: 0.8985 - val_auc: 0.7376 - val_loss: 0.3136
Epoch 7/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9412 - auc: 0.9484 - loss: 0.2293 - val_acc: 0.8947 - val_auc: 0.7444 - val_loss: 0.3185
Epoch 8/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9440 - auc: 0.9524 - loss: 0.2199 - val_acc: 0.8985 - val_auc: 0.7476 - val_loss: 0.3226
Epoch 9/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9349 - auc: 0.9545 - loss: 0.2179 - val_acc: 0.8985 - val_auc: 0.7424 - val_loss: 0.3273
Epoch 10/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9422 - auc: 0.9650 - loss: 0.2007 - val_acc: 0.9023 - val_auc: 0.7335 - val_loss: 0.3339
Epoch 11/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9501 - auc: 0.9744 - loss: 0.1869 - val_acc: 0.9023 - val_auc: 0.7327 - val_loss: 0.3383
Epoch 12/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9661 - auc: 0.9657 - loss: 0.1828 - val_acc: 0.9023 - val_auc: 0.7422 - val_loss: 0.3445
Epoch 13/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9593 - auc: 0.9844 - loss: 0.1573 - val_acc: 0.9023 - val_auc: 0.7432 - val_loss: 0.3524
Epoch 14/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9589 - auc: 0.9798 - loss: 0.1622 - val_acc: 0.8947 - val_auc: 0.7313 - val_loss: 0.3616
Epoch 15/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9541 - auc: 0.9784 - loss: 0.1649 - val_acc: 0.9023 - val_auc: 0.7177 - val_loss: 0.3697
Epoch 16/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - auc: 0.9836 - loss: 0.1532 - val_acc: 0.8985 - val_auc: 0.7208 - val_loss: 0.3733
Epoch 17/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9556 - auc: 0.9823 - loss: 0.1562 - val_acc: 0.8985 - val_auc: 0.7227 - val_loss: 0.3818
Epoch 18/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9785 - auc: 0.9898 - loss: 0.1297 - val_acc: 0.8910 - val_auc: 0.7256 - val_loss: 0.3853
Epoch 19/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9735 - auc: 0.9874 - loss: 0.1346 - val_acc: 0.9060 - val_auc: 0.7288 - val_loss: 0.3994
Epoch 20/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9771 - auc: 0.9906 - loss: 0.1250 - val_acc: 0.8947 - val_auc: 0.7279 - val_loss: 0.4045
Epoch 21/400
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9702 - auc: 0.9849 - loss: 0.1321 - val_acc: 0.9135 - val_auc: 0.7167 - val_loss: 0.4176

In [51]:
y_prob = model.predict(X_test_scaled).ravel()

print("\nProbability stats:")
print("Min:", float(y_prob.min()), "Max:", float(y_prob.max()), "Mean:", float(y_prob.mean()))
neg_probs = y_prob[y_test.values == 0]
pos_probs = y_prob[y_test.values == 1]
print("Neg probs -> Min:", float(neg_probs.min()), "Max:", float(neg_probs.max()), "Mean:", float(neg_probs.mean()))
print("Pos probs -> Min:", float(pos_probs.min()), "Max:", float(pos_probs.max()), "Mean:", float(pos_probs.mean()))

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

Probability stats:
Min: 0.2838023006916046 Max: 0.9996787905693054 Mean: 0.8921363353729248
Neg probs -> Min: 0.44282811880111694 Max: 0.9990411400794983 Mean: 0.7645570039749146
Pos probs -> Min: 0.2838023006916046 Max: 0.9996787905693054 Mean: 0.9034302830696106

In [52]:
best_t, best_ba = 0.5, -1.0
for t in np.arange(0.05, 0.96, 0.01):
    y_pred_t = (y_prob >= t).astype(int)
    ba = balanced_accuracy_score(y_test, y_pred_t)
    if ba > best_ba:
        best_ba, best_t = ba, t

print("\nBest threshold (Balanced Accuracy):", round(best_t, 2), "Best BA:", round(best_ba, 4))

# Final predictions with best threshold
y_pred = (y_prob >= best_t).astype(int)

Best threshold (Balanced Accuracy): 0.79 Best BA: 0.6871

In [53]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy    = accuracy_score(y_test, y_pred)
sensitivity = tp / (tp + fn) if (tp + fn) else 0.0   # recall
recall      = recall_score(y_test, y_pred)
specificity = tn / (tn + fp) if (tn + fp) else 0.0
f1          = f1_score(y_test, y_pred)

roc_auc = roc_auc_score(y_test, y_prob)

print("\nConfusion Matrix:")
print("TN FP")
print(tn, fp)
print("FN TP")
print(fn, tp)

print(f"\nAccuracy     : {accuracy:.4f}")
print(f"Sensitivity  : {sensitivity:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"Specificity  : {specificity:.4f}")
print(f"F1 Score     : {f1:.4f}")
print(f"ROC-AUC      : {roc_auc:.4f}")
print(f"Balanced Acc : {balanced_accuracy_score(y_test, y_pred):.4f}")

Confusion Matrix:
TN FP
14 13
FN TP
44 261

Accuracy     : 0.8283
Sensitivity  : 0.8557
Recall       : 0.8557
Specificity  : 0.5185
F1 Score     : 0.9016
ROC-AUC      : 0.7349
Balanced Acc : 0.6871

# Optuna

In [57]:
import numpy as np
import pandas as pd
import optuna

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import balanced_accuracy_score, roc_auc_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers


classes = np.unique(y_train)
weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weights = {int(classes[0]): float(weights[0]), int(classes[1]): float(weights[1])}
print("Class weights:", class_weights)


def build_ann(trial, input_dim: int):
    n_layers = trial.suggest_int("n_layers", 1, 4)
    first_units = trial.suggest_int("units_0", 32, 256, step=32)

    l2_val = trial.suggest_float("l2", 1e-6, 1e-2, log=True)
    dropout = trial.suggest_float("dropout", 0.0, 0.5)
    lr = trial.suggest_float("lr", 1e-5, 5e-3, log=True)

    model = keras.Sequential()
    model.add(layers.Input(shape=(input_dim,)))

    # First layer
    model.add(layers.Dense(
        first_units,
        activation="relu",
        kernel_regularizer=regularizers.l2(l2_val)
    ))
    if trial.suggest_categorical("use_bn_0", [True, False]):
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(dropout))

    # Additional hidden layers
    units_prev = first_units
    for i in range(1, n_layers):
        units_i = trial.suggest_int(f"units_{i}", 16, units_prev, step=16)
        model.add(layers.Dense(
            units_i,
            activation="relu",
            kernel_regularizer=regularizers.l2(l2_val)
        ))
        if trial.suggest_categorical(f"use_bn_{i}", [True, False]):
            model.add(layers.BatchNormalization())
        model.add(layers.Dropout(dropout))
        units_prev = units_i

    # Output
    model.add(layers.Dense(1, activation="sigmoid"))

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss="binary_crossentropy",
        metrics=[keras.metrics.AUC(name="auc")]
    )
    return model


def objective(trial):
    tf.keras.backend.clear_session()

    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64, 128])
    epochs = 400

    model = build_ann(trial, input_dim=X_train_scaled.shape[1])

    early_stop = keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=20,
        restore_best_weights=True
    )

    model.fit(
        X_train_scaled, y_train,
        validation_split=0.2,
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[early_stop],
        class_weight=class_weights,
        verbose=0
    )


    y_prob = model.predict(X_test_scaled, verbose=0).ravel()

    best_ba = -1
    for t in np.arange(0.05, 0.96, 0.01):
        y_pred = (y_prob >= t).astype(int)
        ba = balanced_accuracy_score(y_test, y_pred)
        if ba > best_ba:
            best_ba = ba

    return best_ba


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30)  # increase to 50/100 if you want

print("\nBest Balanced Accuracy:", study.best_value)
print("Best Params:\n", study.best_params)


best_params = study.best_params
tf.keras.backend.clear_session()

def build_from_best(input_dim):
    # Rebuild model using best params (same logic as build_ann)
    model = keras.Sequential()
    model.add(layers.Input(shape=(input_dim,)))

    l2_val = best_params["l2"]
    dropout = best_params["dropout"]

    n_layers = best_params["n_layers"]
    units0 = best_params["units_0"]

    model.add(layers.Dense(units0, activation="relu", kernel_regularizer=regularizers.l2(l2_val)))
    if best_params["use_bn_0"]:
        model.add(layers.BatchNormalization())
    model.add(layers.Dropout(dropout))

    units_prev = units0
    for i in range(1, n_layers):
        units_i = best_params[f"units_{i}"]
        model.add(layers.Dense(units_i, activation="relu", kernel_regularizer=regularizers.l2(l2_val)))
        if best_params[f"use_bn_{i}"]:
            model.add(layers.BatchNormalization())
        model.add(layers.Dropout(dropout))
        units_prev = units_i

    model.add(layers.Dense(1, activation="sigmoid"))

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=best_params["lr"]),
        loss="binary_crossentropy",
        metrics=[keras.metrics.AUC(name="auc")]
    )
    return model

final_model = build_from_best(X_train_scaled.shape[1])

early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=25,
    restore_best_weights=True
)

final_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=500,
    batch_size=best_params["batch_size"],
    callbacks=[early_stop],
    class_weight=class_weights,
    verbose=1
)


y_prob = final_model.predict(X_test_scaled, verbose=0).ravel()

# best threshold by balanced accuracy
best_t, best_ba = 0.5, -1
for t in np.arange(0.05, 0.96, 0.01):
    y_pred = (y_prob >= t).astype(int)
    ba = balanced_accuracy_score(y_test, y_pred)
    if ba > best_ba:
        best_ba, best_t = ba, t

y_pred = (y_prob >= best_t).astype(int)

from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

accuracy = accuracy_score(y_test, y_pred)
sensitivity = tp / (tp + fn) if (tp + fn) else 0.0
specificity = tn / (tn + fp) if (tn + fp) else 0.0
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("\nBest threshold:", round(best_t, 2))
print("Confusion Matrix:")
print("TN FP"); print(tn, fp)
print("FN TP"); print(fn, tp)

print(f"\nAccuracy     : {accuracy:.4f}")
print(f"Sensitivity  : {sensitivity:.4f}")
print(f"Specificity  : {specificity:.4f}")
print(f"F1 Score     : {f1:.4f}")
print(f"ROC-AUC      : {roc_auc:.4f}")
print(f"Balanced Acc : {best_ba:.4f}")

[I 2026-02-28 21:02:37,292] A new study created in memory with name: no-name-4bdba9c2-b313-423a-b650-79fc136aa528

Class weights: {0: 6.143518518518518, 1: 0.544298605414274}

[I 2026-02-28 21:02:56,405] Trial 0 finished with value: 0.6982392228293868 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 64, 'l2': 2.7592113317237197e-06, 'dropout': 0.23969651345215293, 'lr': 0.0005737385212327489, 'use_bn_0': False}. Best is trial 0 with value: 0.6982392228293868.
[I 2026-02-28 21:03:12,590] Trial 1 finished with value: 0.6946569520340011 and parameters: {'batch_size': 128, 'n_layers': 3, 'units_0': 256, 'l2': 8.928701287073253e-05, 'dropout': 0.45973895840904994, 'lr': 0.003063247058013408, 'use_bn_0': False, 'units_1': 128, 'use_bn_1': True, 'units_2': 16, 'use_bn_2': True}. Best is trial 0 with value: 0.6982392228293868.
[I 2026-02-28 21:04:14,489] Trial 2 finished with value: 0.7041287188828171 and parameters: {'batch_size': 128, 'n_layers': 3, 'units_0': 128, 'l2': 3.9077613598198475e-05, 'dropout': 0.1526226448052465, 'lr': 1.1662406339879326e-05, 'use_bn_0': False, 'units_1': 80, 'use_bn_1': False, 'units_2': 32, 'use_bn_2': False}. Best is trial 2 with value: 0.7041287188828171.
[I 2026-02-28 21:04:30,095] Trial 3 finished with value: 0.5401335761991499 and parameters: {'batch_size': 64, 'n_layers': 4, 'units_0': 192, 'l2': 0.0024375523774744557, 'dropout': 0.21881660011436155, 'lr': 3.844245997385315e-05, 'use_bn_0': True, 'units_1': 160, 'use_bn_1': False, 'units_2': 64, 'use_bn_2': False, 'units_3': 48, 'use_bn_3': True}. Best is trial 2 with value: 0.7041287188828171.
[I 2026-02-28 21:05:33,415] Trial 4 finished with value: 0.6323011536126291 and parameters: {'batch_size': 128, 'n_layers': 3, 'units_0': 160, 'l2': 1.4716710570117682e-06, 'dropout': 0.3635794721679618, 'lr': 1.4781021853105168e-05, 'use_bn_0': True, 'units_1': 144, 'use_bn_1': False, 'units_2': 144, 'use_bn_2': False}. Best is trial 2 with value: 0.7041287188828171.
[I 2026-02-28 21:05:57,902] Trial 5 finished with value: 0.704007285974499 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 32, 'l2': 2.1303019650626825e-05, 'dropout': 0.1678244187998153, 'lr': 0.0004945413424235657, 'use_bn_0': False}. Best is trial 2 with value: 0.7041287188828171.
[I 2026-02-28 21:06:19,613] Trial 6 finished with value: 0.7225258044930176 and parameters: {'batch_size': 64, 'n_layers': 2, 'units_0': 128, 'l2': 0.008755716391786083, 'dropout': 0.025130566205396387, 'lr': 0.0006878792748399403, 'use_bn_0': False, 'units_1': 96, 'use_bn_1': True}. Best is trial 6 with value: 0.7225258044930176.
[I 2026-02-28 21:06:45,096] Trial 7 finished with value: 0.7525197328476017 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 128, 'l2': 0.0001891353364270665, 'dropout': 0.28607412676429644, 'lr': 0.00023352562807626057, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:07:03,163] Trial 8 finished with value: 0.5411050394656952 and parameters: {'batch_size': 16, 'n_layers': 4, 'units_0': 96, 'l2': 0.0014976639331228429, 'dropout': 0.2503742364401456, 'lr': 6.301255131532381e-05, 'use_bn_0': False, 'units_1': 16, 'use_bn_1': True, 'units_2': 16, 'use_bn_2': True, 'units_3': 16, 'use_bn_3': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:07:35,763] Trial 9 finished with value: 0.7204007285974499 and parameters: {'batch_size': 64, 'n_layers': 3, 'units_0': 192, 'l2': 0.0001252214169033681, 'dropout': 0.11426262058208247, 'lr': 6.196510353322341e-05, 'use_bn_0': True, 'units_1': 48, 'use_bn_1': False, 'units_2': 48, 'use_bn_2': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:07:50,742] Trial 10 finished with value: 0.7108682452944748 and parameters: {'batch_size': 16, 'n_layers': 2, 'units_0': 256, 'l2': 0.000502498659756812, 'dropout': 0.34887158984633354, 'lr': 0.004479515232910979, 'use_bn_0': True, 'units_1': 256, 'use_bn_1': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:08:22,201] Trial 11 finished with value: 0.6332119004250152 and parameters: {'batch_size': 64, 'n_layers': 2, 'units_0': 128, 'l2': 0.009805626470209246, 'dropout': 0.02754553886508286, 'lr': 0.0002582997729741157, 'use_bn_0': True, 'units_1': 96, 'use_bn_1': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:08:35,489] Trial 12 finished with value: 0.7094110503946569 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 96, 'l2': 0.00042882710422264354, 'dropout': 0.01827909413816397, 'lr': 0.0011777711851636353, 'use_bn_0': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:09:43,537] Trial 13 finished with value: 0.6986035215543411 and parameters: {'batch_size': 32, 'n_layers': 2, 'units_0': 160, 'l2': 0.009007152555036518, 'dropout': 0.33077925038981854, 'lr': 0.00013451929382035768, 'use_bn_0': True, 'units_1': 96, 'use_bn_1': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:09:55,672] Trial 14 finished with value: 0.7038251366120218 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 96, 'l2': 7.02294232762073e-06, 'dropout': 0.08901274978841078, 'lr': 0.001231185460127852, 'use_bn_0': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:10:37,951] Trial 15 finished with value: 0.7049787492410443 and parameters: {'batch_size': 64, 'n_layers': 2, 'units_0': 192, 'l2': 0.0016725620046208693, 'dropout': 0.4848369171309012, 'lr': 0.00020253399271431268, 'use_bn_0': True, 'units_1': 192, 'use_bn_1': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:10:58,043] Trial 16 finished with value: 0.7431693989071038 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 32, 'l2': 0.0003111894626177148, 'dropout': 0.29487201170910515, 'lr': 0.0011717887624082936, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:11:13,305] Trial 17 finished with value: 0.7395264116575592 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 32, 'l2': 0.0002295186072074334, 'dropout': 0.4108233701545784, 'lr': 0.0019176175088883563, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:11:40,935] Trial 18 finished with value: 0.7159684274438373 and parameters: {'batch_size': 16, 'n_layers': 1, 'units_0': 64, 'l2': 2.8457549041911818e-05, 'dropout': 0.2870766141003106, 'lr': 0.0003380258051441096, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:12:45,448] Trial 19 finished with value: 0.704796599878567 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 64, 'l2': 0.0006517926099827651, 'dropout': 0.2937766102042666, 'lr': 0.0001070613686413615, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:12:58,052] Trial 20 finished with value: 0.7115361262902247 and parameters: {'batch_size': 64, 'n_layers': 2, 'units_0': 224, 'l2': 0.00010844795097999569, 'dropout': 0.40681276970722813, 'lr': 0.0009327724357159583, 'use_bn_0': True, 'units_1': 224, 'use_bn_1': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:13:13,341] Trial 21 finished with value: 0.7259259259259259 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 32, 'l2': 0.0002310552209992724, 'dropout': 0.4119032298746946, 'lr': 0.0019266300722196976, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:13:27,778] Trial 22 finished with value: 0.707103825136612 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 32, 'l2': 0.00022452959599768833, 'dropout': 0.41007366277158985, 'lr': 0.002242783389309068, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:13:41,490] Trial 23 finished with value: 0.7103825136612021 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 64, 'l2': 4.806074994282547e-05, 'dropout': 0.2943268233115454, 'lr': 0.0016993644103357737, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:13:52,427] Trial 24 finished with value: 0.7072859744990893 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 32, 'l2': 0.00025292190644480504, 'dropout': 0.18772377867434065, 'lr': 0.004115407290370514, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:14:03,762] Trial 25 finished with value: 0.5409836065573771 and parameters: {'batch_size': 32, 'n_layers': 2, 'units_0': 96, 'l2': 1.1931563517445255e-05, 'dropout': 0.36679907232443254, 'lr': 0.0004267181102074223, 'use_bn_0': True, 'units_1': 16, 'use_bn_1': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:14:24,198] Trial 26 finished with value: 0.696114146933819 and parameters: {'batch_size': 128, 'n_layers': 1, 'units_0': 64, 'l2': 0.0012506881035362143, 'dropout': 0.43526839498562764, 'lr': 0.0009048386814226216, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:14:40,882] Trial 27 finished with value: 0.7267759562841529 and parameters: {'batch_size': 16, 'n_layers': 2, 'units_0': 32, 'l2': 0.003236343583110033, 'dropout': 0.30655742480350656, 'lr': 0.0029760980775489446, 'use_bn_0': True, 'units_1': 16, 'use_bn_1': False}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:15:04,475] Trial 28 finished with value: 0.6802064359441409 and parameters: {'batch_size': 64, 'n_layers': 1, 'units_0': 224, 'l2': 6.838671608070398e-05, 'dropout': 0.25203611900967376, 'lr': 0.00018598890979426935, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.
[I 2026-02-28 21:15:24,191] Trial 29 finished with value: 0.7265938069216757 and parameters: {'batch_size': 32, 'n_layers': 1, 'units_0': 64, 'l2': 0.0008029944782738558, 'dropout': 0.49660558844426045, 'lr': 0.0006468412444967212, 'use_bn_0': True}. Best is trial 7 with value: 0.7525197328476017.

Best Balanced Accuracy: 0.7525197328476017
Best Params:
 {'batch_size': 64, 'n_layers': 1, 'units_0': 128, 'l2': 0.0001891353364270665, 'dropout': 0.28607412676429644, 'lr': 0.00023352562807626057, 'use_bn_0': True}
Epoch 1/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 5s 158ms/step - auc: 0.4619 - loss: 0.9841 - val_auc: 0.5180 - val_loss: 0.5252
Epoch 2/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.5681 - loss: 0.8260 - val_auc: 0.5440 - val_loss: 0.5407
Epoch 3/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.5690 - loss: 0.8081 - val_auc: 0.5692 - val_loss: 0.5552
Epoch 4/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.5899 - loss: 0.7779 - val_auc: 0.5897 - val_loss: 0.5670
Epoch 5/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.6924 - loss: 0.6908 - val_auc: 0.6086 - val_loss: 0.5767
Epoch 6/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.6526 - loss: 0.7206 - val_auc: 0.6293 - val_loss: 0.5864
Epoch 7/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.6595 - loss: 0.6971 - val_auc: 0.6463 - val_loss: 0.5951
Epoch 8/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.7207 - loss: 0.6454 - val_auc: 0.6611 - val_loss: 0.6012
Epoch 9/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.7188 - loss: 0.6590 - val_auc: 0.6772 - val_loss: 0.6055
Epoch 10/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.7489 - loss: 0.6205 - val_auc: 0.6845 - val_loss: 0.6074
Epoch 11/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.7736 - loss: 0.6028 - val_auc: 0.6923 - val_loss: 0.6073
Epoch 12/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.7945 - loss: 0.5806 - val_auc: 0.7025 - val_loss: 0.6051
Epoch 13/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8213 - loss: 0.5485 - val_auc: 0.7113 - val_loss: 0.6039
Epoch 14/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8047 - loss: 0.5657 - val_auc: 0.7197 - val_loss: 0.6028
Epoch 15/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - auc: 0.8235 - loss: 0.5417 - val_auc: 0.7265 - val_loss: 0.5989
Epoch 16/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.8396 - loss: 0.5372 - val_auc: 0.7347 - val_loss: 0.5945
Epoch 17/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.8174 - loss: 0.5388 - val_auc: 0.7424 - val_loss: 0.5887
Epoch 18/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8613 - loss: 0.4972 - val_auc: 0.7475 - val_loss: 0.5823
Epoch 19/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8807 - loss: 0.4702 - val_auc: 0.7507 - val_loss: 0.5760
Epoch 20/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.8382 - loss: 0.5153 - val_auc: 0.7556 - val_loss: 0.5694
Epoch 21/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.8792 - loss: 0.4729 - val_auc: 0.7590 - val_loss: 0.5622
Epoch 22/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.8536 - loss: 0.4928 - val_auc: 0.7621 - val_loss: 0.5542
Epoch 23/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8733 - loss: 0.4722 - val_auc: 0.7648 - val_loss: 0.5458
Epoch 24/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9088 - loss: 0.4243 - val_auc: 0.7706 - val_loss: 0.5387
Epoch 25/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.8981 - loss: 0.4353 - val_auc: 0.7755 - val_loss: 0.5323
Epoch 26/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9092 - loss: 0.4292 - val_auc: 0.7783 - val_loss: 0.5250
Epoch 27/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9107 - loss: 0.4167 - val_auc: 0.7807 - val_loss: 0.5168
Epoch 28/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9043 - loss: 0.4193 - val_auc: 0.7837 - val_loss: 0.5082
Epoch 29/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9326 - loss: 0.3905 - val_auc: 0.7855 - val_loss: 0.4990
Epoch 30/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9127 - loss: 0.4025 - val_auc: 0.7850 - val_loss: 0.4913
Epoch 31/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9289 - loss: 0.3864 - val_auc: 0.7865 - val_loss: 0.4860
Epoch 32/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9308 - loss: 0.3816 - val_auc: 0.7855 - val_loss: 0.4806
Epoch 33/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9151 - loss: 0.3986 - val_auc: 0.7852 - val_loss: 0.4751
Epoch 34/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9501 - loss: 0.3459 - val_auc: 0.7860 - val_loss: 0.4684
Epoch 35/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9296 - loss: 0.3753 - val_auc: 0.7874 - val_loss: 0.4629
Epoch 36/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9285 - loss: 0.3772 - val_auc: 0.7884 - val_loss: 0.4563
Epoch 37/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9522 - loss: 0.3436 - val_auc: 0.7891 - val_loss: 0.4489
Epoch 38/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9547 - loss: 0.3347 - val_auc: 0.7907 - val_loss: 0.4422
Epoch 39/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9546 - loss: 0.3280 - val_auc: 0.7923 - val_loss: 0.4356
Epoch 40/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9442 - loss: 0.3423 - val_auc: 0.7924 - val_loss: 0.4297
Epoch 41/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9579 - loss: 0.3166 - val_auc: 0.7931 - val_loss: 0.4243
Epoch 42/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9349 - loss: 0.3514 - val_auc: 0.7923 - val_loss: 0.4203
Epoch 43/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9643 - loss: 0.3061 - val_auc: 0.7940 - val_loss: 0.4150
Epoch 44/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9675 - loss: 0.2934 - val_auc: 0.7954 - val_loss: 0.4092
Epoch 45/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9573 - loss: 0.3082 - val_auc: 0.7969 - val_loss: 0.4042
Epoch 46/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9611 - loss: 0.3009 - val_auc: 0.7971 - val_loss: 0.3987
Epoch 47/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9768 - loss: 0.2756 - val_auc: 0.7983 - val_loss: 0.3941
Epoch 48/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9640 - loss: 0.2995 - val_auc: 0.7990 - val_loss: 0.3905
Epoch 49/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9633 - loss: 0.2904 - val_auc: 0.7985 - val_loss: 0.3862
Epoch 50/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9806 - loss: 0.2566 - val_auc: 0.7997 - val_loss: 0.3814
Epoch 51/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9685 - loss: 0.2749 - val_auc: 0.8008 - val_loss: 0.3763
Epoch 52/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9653 - loss: 0.2824 - val_auc: 0.8026 - val_loss: 0.3730
Epoch 53/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9656 - loss: 0.2838 - val_auc: 0.8026 - val_loss: 0.3704
Epoch 54/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9633 - loss: 0.2831 - val_auc: 0.8029 - val_loss: 0.3669
Epoch 55/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9694 - loss: 0.2695 - val_auc: 0.8016 - val_loss: 0.3653
Epoch 56/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9695 - loss: 0.2728 - val_auc: 0.8023 - val_loss: 0.3625
Epoch 57/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9716 - loss: 0.2695 - val_auc: 0.8038 - val_loss: 0.3592
Epoch 58/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9781 - loss: 0.2440 - val_auc: 0.8051 - val_loss: 0.3563
Epoch 59/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9722 - loss: 0.2552 - val_auc: 0.8052 - val_loss: 0.3530
Epoch 60/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9774 - loss: 0.2566 - val_auc: 0.8068 - val_loss: 0.3502
Epoch 61/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9866 - loss: 0.2207 - val_auc: 0.8065 - val_loss: 0.3470
Epoch 62/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9792 - loss: 0.2463 - val_auc: 0.8075 - val_loss: 0.3430
Epoch 63/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9809 - loss: 0.2330 - val_auc: 0.8080 - val_loss: 0.3402
Epoch 64/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9806 - loss: 0.2250 - val_auc: 0.8076 - val_loss: 0.3372
Epoch 65/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9808 - loss: 0.2301 - val_auc: 0.8080 - val_loss: 0.3337
Epoch 66/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9759 - loss: 0.2411 - val_auc: 0.8088 - val_loss: 0.3313
Epoch 67/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9835 - loss: 0.2148 - val_auc: 0.8079 - val_loss: 0.3291
Epoch 68/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9821 - loss: 0.2248 - val_auc: 0.8075 - val_loss: 0.3276
Epoch 69/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9842 - loss: 0.2212 - val_auc: 0.8067 - val_loss: 0.3255
Epoch 70/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9806 - loss: 0.2146 - val_auc: 0.8059 - val_loss: 0.3238
Epoch 71/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9843 - loss: 0.2066 - val_auc: 0.8066 - val_loss: 0.3223
Epoch 72/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9866 - loss: 0.2023 - val_auc: 0.8068 - val_loss: 0.3190
Epoch 73/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9838 - loss: 0.2182 - val_auc: 0.8081 - val_loss: 0.3181
Epoch 74/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9897 - loss: 0.1940 - val_auc: 0.8095 - val_loss: 0.3159
Epoch 75/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9888 - loss: 0.1957 - val_auc: 0.8092 - val_loss: 0.3143
Epoch 76/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9853 - loss: 0.2111 - val_auc: 0.8116 - val_loss: 0.3135
Epoch 77/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9868 - loss: 0.1981 - val_auc: 0.8103 - val_loss: 0.3133
Epoch 78/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9879 - loss: 0.1903 - val_auc: 0.8099 - val_loss: 0.3113
Epoch 79/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - auc: 0.9905 - loss: 0.1801 - val_auc: 0.8106 - val_loss: 0.3086
Epoch 80/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9878 - loss: 0.1917 - val_auc: 0.8112 - val_loss: 0.3071
Epoch 81/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9879 - loss: 0.1895 - val_auc: 0.8115 - val_loss: 0.3062
Epoch 82/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9896 - loss: 0.1824 - val_auc: 0.8114 - val_loss: 0.3049
Epoch 83/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9929 - loss: 0.1663 - val_auc: 0.8120 - val_loss: 0.3040
Epoch 84/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9923 - loss: 0.1742 - val_auc: 0.8123 - val_loss: 0.3023
Epoch 85/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9907 - loss: 0.1737 - val_auc: 0.8145 - val_loss: 0.2998
Epoch 86/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9926 - loss: 0.1602 - val_auc: 0.8150 - val_loss: 0.2973
Epoch 87/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9952 - loss: 0.1638 - val_auc: 0.8156 - val_loss: 0.2962
Epoch 88/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9944 - loss: 0.1572 - val_auc: 0.8153 - val_loss: 0.2950
Epoch 89/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9934 - loss: 0.1560 - val_auc: 0.8164 - val_loss: 0.2942
Epoch 90/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9956 - loss: 0.1524 - val_auc: 0.8170 - val_loss: 0.2919
Epoch 91/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9955 - loss: 0.1527 - val_auc: 0.8161 - val_loss: 0.2915
Epoch 92/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9910 - loss: 0.1607 - val_auc: 0.8150 - val_loss: 0.2908
Epoch 93/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9977 - loss: 0.1477 - val_auc: 0.8161 - val_loss: 0.2898
Epoch 94/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9931 - loss: 0.1628 - val_auc: 0.8151 - val_loss: 0.2892
Epoch 95/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9948 - loss: 0.1454 - val_auc: 0.8159 - val_loss: 0.2885
Epoch 96/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9941 - loss: 0.1396 - val_auc: 0.8149 - val_loss: 0.2872
Epoch 97/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9950 - loss: 0.1408 - val_auc: 0.8160 - val_loss: 0.2864
Epoch 98/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9934 - loss: 0.1351 - val_auc: 0.8150 - val_loss: 0.2863
Epoch 99/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9974 - loss: 0.1311 - val_auc: 0.8137 - val_loss: 0.2857
Epoch 100/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9970 - loss: 0.1272 - val_auc: 0.8145 - val_loss: 0.2835
Epoch 101/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9983 - loss: 0.1258 - val_auc: 0.8169 - val_loss: 0.2812
Epoch 102/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9982 - loss: 0.1240 - val_auc: 0.8179 - val_loss: 0.2792
Epoch 103/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9971 - loss: 0.1173 - val_auc: 0.8189 - val_loss: 0.2785
Epoch 104/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9963 - loss: 0.1301 - val_auc: 0.8194 - val_loss: 0.2795
Epoch 105/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9974 - loss: 0.1198 - val_auc: 0.8186 - val_loss: 0.2799
Epoch 106/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9991 - loss: 0.1174 - val_auc: 0.8176 - val_loss: 0.2795
Epoch 107/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9968 - loss: 0.1291 - val_auc: 0.8168 - val_loss: 0.2802
Epoch 108/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9995 - loss: 0.1119 - val_auc: 0.8166 - val_loss: 0.2797
Epoch 109/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9968 - loss: 0.1225 - val_auc: 0.8176 - val_loss: 0.2795
Epoch 110/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9989 - loss: 0.1086 - val_auc: 0.8179 - val_loss: 0.2796
Epoch 111/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9978 - loss: 0.1225 - val_auc: 0.8190 - val_loss: 0.2789
Epoch 112/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9985 - loss: 0.1119 - val_auc: 0.8214 - val_loss: 0.2772
Epoch 113/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9974 - loss: 0.1164 - val_auc: 0.8239 - val_loss: 0.2752
Epoch 114/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9967 - loss: 0.1149 - val_auc: 0.8211 - val_loss: 0.2746
Epoch 115/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9974 - loss: 0.1142 - val_auc: 0.8221 - val_loss: 0.2743
Epoch 116/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9975 - loss: 0.1150 - val_auc: 0.8229 - val_loss: 0.2748
Epoch 117/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9970 - loss: 0.1126 - val_auc: 0.8212 - val_loss: 0.2757
Epoch 118/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9967 - loss: 0.1119 - val_auc: 0.8209 - val_loss: 0.2752
Epoch 119/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9968 - loss: 0.1133 - val_auc: 0.8228 - val_loss: 0.2751
Epoch 120/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9988 - loss: 0.1091 - val_auc: 0.8242 - val_loss: 0.2752
Epoch 121/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9982 - loss: 0.0974 - val_auc: 0.8218 - val_loss: 0.2739
Epoch 122/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9986 - loss: 0.1021 - val_auc: 0.8224 - val_loss: 0.2741
Epoch 123/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9980 - loss: 0.1010 - val_auc: 0.8237 - val_loss: 0.2745
Epoch 124/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9993 - loss: 0.0958 - val_auc: 0.8215 - val_loss: 0.2744
Epoch 125/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9987 - loss: 0.0976 - val_auc: 0.8205 - val_loss: 0.2748
Epoch 126/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9988 - loss: 0.0943 - val_auc: 0.8219 - val_loss: 0.2746
Epoch 127/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9981 - loss: 0.0938 - val_auc: 0.8219 - val_loss: 0.2747
Epoch 128/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9976 - loss: 0.0984 - val_auc: 0.8232 - val_loss: 0.2742
Epoch 129/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9970 - loss: 0.0960 - val_auc: 0.8234 - val_loss: 0.2744
Epoch 130/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9991 - loss: 0.0915 - val_auc: 0.8217 - val_loss: 0.2744
Epoch 131/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9987 - loss: 0.0946 - val_auc: 0.8227 - val_loss: 0.2743
Epoch 132/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9994 - loss: 0.0817 - val_auc: 0.8224 - val_loss: 0.2740
Epoch 133/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9986 - loss: 0.0875 - val_auc: 0.8230 - val_loss: 0.2734
Epoch 134/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9989 - loss: 0.0891 - val_auc: 0.8230 - val_loss: 0.2735
Epoch 135/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9984 - loss: 0.0965 - val_auc: 0.8252 - val_loss: 0.2746
Epoch 136/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9995 - loss: 0.0878 - val_auc: 0.8225 - val_loss: 0.2763
Epoch 137/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9995 - loss: 0.0811 - val_auc: 0.8220 - val_loss: 0.2770
Epoch 138/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9995 - loss: 0.0764 - val_auc: 0.8228 - val_loss: 0.2768
Epoch 139/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9993 - loss: 0.0758 - val_auc: 0.8234 - val_loss: 0.2773
Epoch 140/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9989 - loss: 0.0912 - val_auc: 0.8242 - val_loss: 0.2778
Epoch 141/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9989 - loss: 0.0795 - val_auc: 0.8250 - val_loss: 0.2786
Epoch 142/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9992 - loss: 0.0875 - val_auc: 0.8239 - val_loss: 0.2798
Epoch 143/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9985 - loss: 0.0935 - val_auc: 0.8237 - val_loss: 0.2808
Epoch 144/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9996 - loss: 0.0778 - val_auc: 0.8229 - val_loss: 0.2825
Epoch 145/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9974 - loss: 0.0873 - val_auc: 0.8128 - val_loss: 0.2820
Epoch 146/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9998 - loss: 0.0712 - val_auc: 0.8129 - val_loss: 0.2820
Epoch 147/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9999 - loss: 0.0719 - val_auc: 0.8156 - val_loss: 0.2817
Epoch 148/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9987 - loss: 0.0822 - val_auc: 0.8138 - val_loss: 0.2829
Epoch 149/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9995 - loss: 0.0701 - val_auc: 0.8152 - val_loss: 0.2817
Epoch 150/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9998 - loss: 0.0718 - val_auc: 0.8150 - val_loss: 0.2815
Epoch 151/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 1.0000 - loss: 0.0687 - val_auc: 0.8128 - val_loss: 0.2833
Epoch 152/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9999 - loss: 0.0719 - val_auc: 0.8126 - val_loss: 0.2835
Epoch 153/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9997 - loss: 0.0720 - val_auc: 0.8141 - val_loss: 0.2821
Epoch 154/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9987 - loss: 0.0725 - val_auc: 0.8143 - val_loss: 0.2810
Epoch 155/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9999 - loss: 0.0649 - val_auc: 0.8153 - val_loss: 0.2815
Epoch 156/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9985 - loss: 0.0701 - val_auc: 0.8161 - val_loss: 0.2820
Epoch 157/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - auc: 0.9997 - loss: 0.0648 - val_auc: 0.8159 - val_loss: 0.2825
Epoch 158/500
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - auc: 0.9996 - loss: 0.0686 - val_auc: 0.8163 - val_loss: 0.2826

Best threshold: 0.73
Confusion Matrix:
TN FP
16 11
FN TP
42 263

Accuracy     : 0.8404
Sensitivity  : 0.8623
Specificity  : 0.5926
F1 Score     : 0.9085
ROC-AUC      : 0.7831
Balanced Acc : 0.7274